name: Pre-deployment tests

concurrency:
  group: testing
  cancel-in-progress: true

on:
  push:
    branches:
      - prod

jobs:
  testing:
    runs-on: ubuntu-latest
    environment: testing
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
      CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22.19.0
      - name: Install dependencies
        run: npm install
      - name: Apply all pending migrations to the database
        run: npx prisma migrate deploy
      - name: Run all test runners
        run: npm run test